#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
. $(dirname $SOURCE)/init.sh


cd $basedir
spigotVer=$(cat current-spigot)

decompile=$(ls -lat Spigot/work/ | grep decompile | head -n 1 | awk '{print $9}')
mkdir -p mc-dev/src/net/minecraft/server

cd mc-dev
if [ ! -d ".git" ]; then
	git init
fi

cd $basedir
cp $decompile/*.java .

cd src/net/minecraft/server

base="$basedir/EmpireCraft-Server/src/main/java/net/minecraft/server"
for file in $(/bin/ls $base)
do
	if [ -f "$file" ]; then
		rm -f "$file"
	fi
done
git add . -A
git commit . -m "mc-dev"

git tag -a "$spigotVer" -F - 2>/dev/null
pushRepo $basedir/mc-dev git@bitbucket.org:starlis/mc-dev
